---

- name: Import OS-specific vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install VSCode
  include_tasks: "install_{{ ansible_os_family }}.yml"

- name: Configure VSCode
  include_tasks: configure.yml
