---

- name: Import OS-specific vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install VSCode
  include_tasks: "install_{{ ansible_os_family }}.yml"

- name: Configure VSCode
  include_tasks: configure.yml

- name: Install Python specific dependencies
  include_tasks: python.yml
  when:
    - "'ms-python.python' in vscode_extensions"
    - "vscode_python_install|bool"
